//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTNhom3_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CTHoaDons = new HashSet<CTHoaDon>();
        }
    
        public string MaSP { get; set; }
        public string MaNCC { get; set; }
        public string MaLoai { get; set; }
        [DisplayName("Tên S?n Ph?m")]
        public string TenSP { get; set; }
        public string MoTaSP { get; set; }
        public string AnhDaiDien { get; set; }
        public Nullable<int> DonGia { get; set; }
        public string DonViTinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHoaDon> CTHoaDons { get; set; }
        public virtual Loai Loai { get; set; }
        public virtual NCC NCC { get; set; }
    }
}
