//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTNhom3_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThamSo
    {
        public string MaTS { get; set; }
        public string TenTS { get; set; }
        public string DonViTinh { get; set; }
        public Nullable<int> GiaTri { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
    }
}
